<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5d9c331e19e3a',
        'title' => esc_html__('Navbar Style', 'albion'),
        'fields' => array(
            array(
                'key' => 'field_5d9c3393e15d2',
                'label' => esc_html__('Choose Navigation Style', 'albion'),
                'name' => 'choose_navigation_style',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    1 => 'Navbar transparent with full width',
                    2 => 'Navbar transparent with container',
                    3 => 'Navbar light with full width',
                    4 => 'Navbar light with container',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => '',
                'layout' => 'vertical',
                'return_format' => 'value',
                'save_other_choice' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'default',
                ),
            ),
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'elementor_header_footer',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'side',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_5da40c65c6855',
        'title' => esc_html__('Pages Option', 'albion'),
        'fields' => array(
            array(
                'key' => 'field_5da40c6f4c037',
                'label' => esc_html__('Page Banner Hide?', 'albion'),
                'name' => 'page_banner_hide',
                'type' => 'checkbox',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'yes' => 'Yes',
                ),
                'allow_custom' => 0,
                'default_value' => array(
                ),
                'layout' => 'vertical',
                'toggle' => 0,
                'return_format' => 'value',
                'save_custom' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'default',
                ),
            ),
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'elementor_header_footer',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'side',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_5da699c015f77',
        'title' => esc_html__('Post Format Video', 'albion'),
        'fields' => array(
            array(
                'key' => 'field_5da699efa948a',
                'label' => esc_html__('Video Link', 'albion'),
                'name' => 'video_link',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_format',
                    'operator' => '==',
                    'value' => 'video',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'side',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_5df8765420f1e',
        'title' => esc_html__('Projects Meta Info', 'albion'),
        'fields' => array(
            array(
                'key' => 'field_5df8766b91120',
                'label' => esc_html__('Projects Images', 'albion'),
                'name' => 'projects_images',
                'type' => 'gallery',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'medium',
                'insert' => 'append',
                'library' => 'all',
                'min' => '',
                'max' => '',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5df8767f91121',
                'label' => esc_html__('Information List', 'albion'),
                'name' => 'information_list',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5df8769b91122',
                        'label' => esc_html__('Title', 'albion'),
                        'name' => 'title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5df8769f91123',
                        'label' => esc_html__('Title Value', 'albion'),
                        'name' => 'title_value',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5df876af91124',
                        'label' => esc_html__('Is Link?', 'albion'),
                        'name' => 'is_link',
                        'type' => 'checkbox',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'yes' => 'Yes',
                        ),
                        'allow_custom' => 0,
                        'default_value' => array(
                        ),
                        'layout' => 'vertical',
                        'toggle' => 0,
                        'return_format' => 'value',
                        'save_custom' => 0,
                    ),
                    array(
                        'key' => 'field_5df876cb91125',
                        'label' => esc_html__('Link URL', 'albion'),
                        'name' => 'link_url',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5df876af91124',
                                    'operator' => '!=empty',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'project',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_5d9d6515e978a',
        'title' => esc_html__('Services Featured Category Meta', 'albion'),
        'fields' => array(
            array(
                'key' => 'field_5d9d65c48f9cf',
                'label' => esc_html__('Card active?', 'albion'),
                'name' => 'card_active',
                'type' => 'checkbox',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'yes' => 'Yes',
                ),
                'allow_custom' => 0,
                'default_value' => array(
                ),
                'layout' => 'vertical',
                'toggle' => 0,
                'return_format' => 'value',
                'save_custom' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'service',
                ),
                array(
                    'param' => 'post_taxonomy',
                    'operator' => '==',
                    'value' => 'service_cat:featured',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_5d9c70445d9b7',
        'title' => esc_html__('Services Meta Info', 'albion'),
        'fields' => array(
            array(
                'key' => 'field_5d9c706084f8b',
                'label' => esc_html__('Choose Icon', 'albion'),
                'name' => 'choose_icon',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'flaticon-income' => 'flaticon-income',
                    'flaticon-automatic' => 'flaticon-automatic',
                    'flaticon-locked' => 'flaticon-locked',
                    'flaticon-molecular' => 'flaticon-molecular',
                    'flaticon-gear' => 'flaticon-gear',
                    'flaticon-ceo' => 'flaticon-ceo',
                    'flaticon-commerce-and-shopping' => 'flaticon-commerce-and-shopping',
                    'flaticon-search' => 'flaticon-search',
                    'flaticon-robot' => 'flaticon-robot',
                    'flaticon-artificial-intelligence' => 'flaticon-artificial-intelligence',
                    'flaticon-machine-learning' => 'flaticon-machine-learning',
                    'flaticon-play-button' => 'flaticon-play-button',
                    'flaticon-tick' => 'flaticon-tick',
                    'flaticon-add' => 'flaticon-add',
                    'flaticon-remove' => 'flaticon-remove',
                    'flaticon-facebook-letter-logo' => 'flaticon-facebook-letter-logo',
                    'flaticon-twitter' => 'flaticon-twitter',
                    'flaticon-instagram-logo' => 'flaticon-instagram-logo',
                    'flaticon-youtube-play-button' => 'flaticon-youtube-play-button',
                    'flaticon-left-quote' => 'flaticon-left-quote',
                    'flaticon-right-chevron' => 'flaticon-right-chevron',
                    'flaticon-left-chevron' => 'flaticon-left-chevron',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'service',
                ),
                array(
                    'param' => 'post_taxonomy',
                    'operator' => '!=',
                    'value' => 'service_cat:featured-solutions',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    endif;